server:
  port: 10086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: 'shopping-shop-ms'
  datasource:
    username: root
    password: root
    url: 'jdbc:mysql://localhost:3306/shopping_websitedb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai'
pagehelper:
  helper-dialect: mysql
  reasonable: true
# MinIO对象存储相关配置
minio:
  endpoint:  http://127.0.0.1:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
file:
  staticAccessPath: '/upload/**'
  uploadFolder: 'D:\\pictures'